### ISSUE TITLE
Remove string test. 

### ISSUE THREAD

**Issue by mike-eiden** [rpharrigan211/cs4500-assignment1-part2#10]
Hi can we please remove this test? It has nothing to do with testing the queue (the function is never used once queues are the unit under test) which is what this file should be checking.  It also doesn't match the standard string interface given on piazza.  It also gives away an implementation detail by accessing a field of String which at this point should have no fields. 

https://github.com/rpharrigan211/cs4500-assignment1-part2/blob/3b27b9d422318ebefc8ad47b43b69be12ca87974/test-queue.cpp#L42

**Comment by rpharrigan211** [comment]
Fair point.
