### ISSUE TITLE
Two size() funcs in string.h

### ISSUE THREAD

**Issue by kachmarma** [rpharrigan211/cs4500-assignment1-part2#13]
Hello, there are two size() methods in string.h. Thanks!

**Comment by thomas-vaiarella** [comment]
Also, the other two customers of Matt and I have adopted the universal string.h and object.h APIs seen at this Piazza post https://piazza.com/class/k51bluky59n2jr?cid=345. It could be beneficial for you to swap the APIs in your repository for these. It will help you to come to a consensus with your other spec teams if they have/will adopt these APIs.

**Comment by rpharrigan211** [comment]
Thomas,
Makes sense. We fixed that and implemented a String API very similar to what was in the Piazza post (we also removed the strCopy() function as it seems pretty useless right now).
