### ISSUE TITLE
The necessity of function remove()

### ISSUE THREAD

**Issue by EricXuZh** [rpharrigan211/cs4500-assignment1-part2#2]
Is there a reason why remove() is included in the api for queue? I've looked around the internet for a little bit and no other implementation of queue in any language provides the option to return a copy of an element upon popping it out. Would it be alright to remove it?

**Comment by DNishanth** [comment]
We based remove() off of pop() from Java queues. Pop() returns the element that's being removed, but we have no problems with making remove() void in our queue api. If we need to copy an element before removing, we can just make a call to head().

**Comment by DNishanth** [comment]
Just made the changes to the remove() and the tests.
