### ISSUE TITLE
test-queue.cpp calls for allowing mixed types of queues

### ISSUE THREAD

**Issue by mike-eiden** [rpharrigan211/cs4500-assignment1-part2#5]
Hi, 
I don't think that the Queue spec is supposed to allow a queue that contains both objects and strings.  It should be one or the other, but currently in the tests there are tests that test that both types can be added to the same queue.

**Comment by rpharrigan211** [comment]
Hey Mike,
We're consulting about that rn, should be fixed soon.

**Comment by rpharrigan211** [comment]
We decided to create a StringQueue class which extends Queue, but allows only Strings. We also updated test-queue.cpp to accommodate this change.
